service: aws-ruby
frameworkVersion: '2'

plugins:
  - serverless-localstack
custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://127.0.0.1

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
